# Generated by Django 4.2.25 on 2025-11-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_usuario_projeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao_tarefa',
            field=models.CharField(max_length=100),
        ),
    ]
